language: python
python:
    - "2.7"
notifications:
    email: false
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script:
    - py.test --cov={envsitepackagesdir}/ironman --doctest-glob='docs/*.rst' --strict --verbose --tb=long docs tests
    - py.test --doctest-modules --strict --verbose --tb=long ironman
after_success:
    coveralls
