language: python
python:
    - "2.7"
notifications:
    email: false
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script:
    - "coverage run --source=ironman setup.py test"
after_success:
    coveralls
