language: python
python:
    - "2.7"
notifications:
    email: false
install:
    - "pip install -r requirements.txt"
    - "pip install tox codecov"
script:
    - tox
    #- coverage run `which tox`
after_success:
    - codecov
