language: python
python:
    - "2.7"
notifications:
    email: false
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script:
    - tox
    - tox -e doctest-modules
    - tox -e coverage
after_success:
    coveralls
