language: python
python:
  - "2.7"
install:
    - "pip install -r requirements.txt"
    - "pip install coveralls"
script:
    - "coverage run --source=ironman setup.py test"
    - "tox"
after_success:
    coveralls
